version: '3.9'
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: synergy
      MYSQL_USER: synergy
      MYSQL_PASSWORD: synergy_pw
      MYSQL_ROOT_PASSWORD: root_pw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db_data:

